# Tratamento de Erro em Acesso a Dicionários:

# Acesse um dicionário com uma chave inexistente e trate a exceção KeyError. ​

dicio = {"00":0,"01":1,"02":2,"03":3}


int(input("Digite um valor para o dicionário"))
print(f"Valores: {dicio}")